/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i3 from './app';
export declare const RenderType_App: i0.RendererType2;
export declare function View_App_0(_l: any): i0.ɵViewDefinition;
export declare function View_App_Host_0(_l: any): i0.ɵViewDefinition;
export declare const AppNgFactory: i0.ComponentFactory<i3.App>;
