/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from '@angular/core';
import * as import1 from './app';
export declare const RenderType_App: import0.RendererType2;
export declare function View_App_0(): import0.ɵViewDefinition;
export declare const AppNgFactory: import0.ComponentFactory<import1.App>;
