/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import1 from './module.lazy';
export declare const AppLazyModuleNgFactory: import0.NgModuleFactory<import1.AppLazyModule>;
