/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from '@angular/core';
import * as import1 from './module';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
