/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './search';
export declare const RenderType_Search: i0.RendererType2;
export declare function View_Search_0(_l: any): i0.ɵViewDefinition;
export declare function View_Search_Host_0(_l: any): i0.ɵViewDefinition;
export declare const SearchNgFactory: i0.ComponentFactory<i1.Search>;
