/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import1 from './search';
export declare const RenderType_Search: import0.RendererType2;
export declare function View_Search_0(l: any): import0.ɵViewDefinition;
export declare const SearchNgFactory: import0.ComponentFactory<import1.Search>;
