/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from '@angular/core';
import * as import1 from './list';
export declare const RenderType_List: import0.RendererType2;
export declare function View_List_0(log: any): import0.ɵViewDefinition;
export declare const ListNgFactory: import0.ComponentFactory<import1.List>;
