/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './list';
export declare const RenderType_List: i0.RendererType2;
export declare function View_List_0(_l: any): i0.ɵViewDefinition;
export declare function View_List_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ListNgFactory: i0.ComponentFactory<i1.List>;
