/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './list.module';
export declare const ListModuleNgFactory: i0.NgModuleFactory<i1.ListModule>;
